#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE=".env.gcp.local"
REGION="us-east1"
ZONE="us-east1-b"
VM_NAME="blankfolio-worker"

banner "Google Cloud: always-free VM for the literature worker"

stage "Install the gcloud CLI"
if command -v gcloud >/dev/null 2>&1; then
  say "gcloud is already installed: $(gcloud --version 2>/dev/null | head -n1)"
else
  say "The gcloud CLI talks to Google Cloud from this terminal."
  if command -v brew >/dev/null 2>&1 && confirm "Install it now with 'brew install --cask gcloud-cli'?"; then
    brew install --cask gcloud-cli
  else
    open_url "https://docs.cloud.google.com/sdk/docs/install-sdk"
    step "Follow the macOS instructions, then open a new terminal and re-run this wizard."
    exit 1
  fi
  if ! command -v gcloud >/dev/null 2>&1; then
    warn "gcloud is installed but not on PATH yet. Open a new terminal and re-run this wizard."
    exit 1
  fi
fi
pause

stage "Sign in to Google Cloud"
say "A browser window opens; sign in with the Google account that will own the VM."
gcloud auth login
note "Signed in as: $(gcloud config get-value account 2>/dev/null)"
pause

stage "Billing account"
say "The free tier still needs a billing account on file; the free VM costs \$0."
open_url "https://console.cloud.google.com/billing"
step "If you have no billing account: click 'Create account', add your card, finish."
step "Copy the Billing account ID (looks like 012345-6789AB-CDEF01)."
note "Your accounts, for reference:"
gcloud billing accounts list --filter=open=true --format="table(name.basename(),displayName)" 2>/dev/null || true
ask GCP_BILLING_ACCOUNT "Billing account ID:"
write_env GCP_BILLING_ACCOUNT "$GCP_BILLING_ACCOUNT"
pause

stage "Create the project"
default_project="blankfolio-worker-$(openssl rand -hex 3)"
existing_project=$(_existing GCP_PROJECT_ID || true)
say "Project IDs are global, so a random suffix keeps it unique."
note "Suggested: ${existing_project:-$default_project}"
ask GCP_PROJECT_ID "Project ID (Enter for the suggestion):"
GCP_PROJECT_ID="${GCP_PROJECT_ID:-${existing_project:-$default_project}}"
if gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  note "Project $GCP_PROJECT_ID already exists; reusing it."
else
  gcloud projects create "$GCP_PROJECT_ID" --name="blankfolio worker"
fi
gcloud config set project "$GCP_PROJECT_ID"
gcloud billing projects link "$GCP_PROJECT_ID" --billing-account="$GCP_BILLING_ACCOUNT"
say "Enabling the Compute Engine and Budgets APIs (can take a minute)…"
gcloud services enable compute.googleapis.com billingbudgets.googleapis.com
write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
pause

stage "Budget alert"
say "An email alert if this billing account ever spends money: at \$0.50 and \$1."
if gcloud billing budgets list --billing-account="$GCP_BILLING_ACCOUNT" \
  --format="value(displayName)" 2>/dev/null | grep -qx "blankfolio worker"; then
  note "Budget 'blankfolio worker' already exists; keeping it."
elif confirm "Create a \$1 monthly budget alert for this project?"; then
  # The Budgets API filters by project number, not project ID.
  project_number=$(gcloud projects describe "$GCP_PROJECT_ID" --format="value(projectNumber)")
  if ! gcloud billing budgets create \
    --billing-account="$GCP_BILLING_ACCOUNT" \
    --display-name="blankfolio worker" \
    --budget-amount=1USD \
    --filter-projects="projects/$project_number" \
    --threshold-rule=percent=0.5 \
    --threshold-rule=percent=1.0; then
    warn "Couldn't create the budget from the CLI; create it in the console instead:"
    open_url "https://console.cloud.google.com/billing/$GCP_BILLING_ACCOUNT/budgets"
    step "Create budget → name 'blankfolio worker' → scope: this project → amount \$1 → alerts at 50% and 100%."
    pause "Press Enter once the budget is saved"
  fi
else
  SKIPPED+=("Budget alert (Billing → Budgets & alerts in the console)")
fi
pause

stage "Create the free e2-micro VM"
say "Free tier: one e2-micro in $REGION with a 30 GB standard disk."
note "Machine e2-micro · zone $ZONE · Debian 12 · 30 GB pd-standard"
if gcloud compute instances describe "$VM_NAME" --zone="$ZONE" >/dev/null 2>&1; then
  note "VM $VM_NAME already exists; reusing it."
elif confirm "Create VM '$VM_NAME' now?"; then
  gcloud compute instances create "$VM_NAME" \
    --zone="$ZONE" \
    --machine-type=e2-micro \
    --image-family=debian-12 \
    --image-project=debian-cloud \
    --boot-disk-size=30GB \
    --boot-disk-type=pd-standard
else
  warn "Skipped VM creation; re-run the wizard when ready."
  exit 1
fi
write_env GCP_ZONE "$ZONE"
write_env GCP_VM_NAME "$VM_NAME"
pause

stage "Install Node.js 24, pnpm and git on the VM"
say "Connecting over SSH (first time: gcloud creates an SSH key; press Enter for no passphrase)."
note "Also adds 2 GB swap so installs and builds fit in the VM's 1 GB of memory."
gcloud compute ssh "$VM_NAME" --zone="$ZONE" --command='
set -e
if [ ! -f /swapfile ]; then
  sudo fallocate -l 2G /swapfile && sudo chmod 600 /swapfile
  sudo mkswap /swapfile && sudo swapon /swapfile
  echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab >/dev/null
fi
if ! command -v node >/dev/null 2>&1 || ! node --version | grep -q "^v24"; then
  curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -
  sudo apt-get install -y nodejs
fi
sudo apt-get install -y git
sudo corepack enable
echo "node $(node --version), git $(git --version | cut -d" " -f3), swap $(free -m | awk "/Swap/ {print \$2}") MB"
'
pause

stage "Done: what's saved"
say "Saved to $ENV_FILE (git-ignored): project, billing account, zone and VM name."
say "The worker's code, service and env are deployed in a later step."
note "SSH in any time:  gcloud compute ssh $VM_NAME --zone=$ZONE"
note "Stop billing risk: gcloud compute instances delete $VM_NAME --zone=$ZONE"
pause "Press Enter to finish"

finish
